import type { StudioGuideDescriptor } from "framediff";

export const studioPlaygroundGuide: StudioGuideDescriptor = {
  id: "studio-playground-tour-v1",
  title: "Studio Playground",
  summary: "A guided acceptance project through a three-level composition graph: authoring, editing, motion, finishing, simulation, generation, audio and delivery.",
  estimatedMinutes: 30,
  steps: [
    {
      id: "orientation",
      phase: "Start here",
      title: "Read the capability map",
      description: "This document composition is the front door to a real nested project rather than a disconnected gallery of demos.",
      try: "Scrub the root timeline and watch the persistent chapter label and progress rail change at every boundary.",
      success: "Each chapter appears at its authored frame and random-access jumps produce the same state as playback.",
      target: { compositionKey: "studio-playground", frame: 90 },
    },
    {
      id: "hierarchy",
      phase: "Start here",
      title: "Open a chapter, then a focused leaf",
      description: "The root has four chapter compositions; each chapter contains focused leaf compositions that can be edited and reused independently.",
      try: "Open Authoring systems from the root timeline, then open Direct manipulation inside it. Use the breadcrumb to return.",
      success: "The breadcrumb shows StudioPlayground → AuthoringChapter → DirectManipulationLab without losing the parent playhead.",
      target: { compositionKey: "authoring-chapter", frame: 60, selection: { kind: "clip", objectId: "author-direct" } },
    },
    {
      id: "canvas",
      phase: "Author",
      title: "Move, resize and undo a stable element",
      description: "Stable element IDs connect direct manipulation, source authority, Inspector values and history.",
      try: "Drag the MOVE card, resize it, then Undo and Redo once.",
      success: "One gesture creates one readable data-fd source edit and one history entry.",
      target: { compositionKey: "direct-manipulation-lab", frame: 60, selection: { kind: "element", objectId: "move-card", ownerItemId: "lab-scene" }, panel: "inspector" },
    },
    {
      id: "properties",
      phase: "Author",
      title: "Edit text, fills and layout",
      description: "Typography, gradients, image fills, flex layout and spacing share one source-backed property ABI.",
      try: "Edit the headline, change its typography, then adjust the gradient angle and a color stop.",
      success: "The preview updates immediately and refresh preserves literal authored values.",
      target: { compositionKey: "rich-properties-lab", frame: 60, selection: { kind: "element", objectId: "rich-headline", ownerItemId: "rich-scene" }, panel: "inspector" },
    },
    {
      id: "gsap",
      phase: "Motion",
      title: "Edit registered GSAP motion",
      description: "Paused GSAP timelines remain source adapters over the absolute FrameDiff frame clock.",
      try: "Move the title-enter key diamond, change its ease and jump backward across it.",
      success: "The same frame resolves identically after non-linear scrubbing and refresh.",
      target: { compositionKey: "gsap-motion-lab", frame: 20, selection: { kind: "animation", objectId: "title-enter" }, panel: "inspector" },
    },
    {
      id: "package-effects",
      phase: "Motion",
      title: "Exercise the public effect modules",
      description: "Character rise, wipe reveal, clip motion, spring math, interpolation and audio fade are composed without wall-clock state.",
      try: "Jump among frames 0, 72, 188 and 72; compare the headline, wipe, path card and spring orb.",
      success: "Returning to frame 72 reproduces the same visual state exactly.",
      target: { compositionKey: "package-effects-lab", frame: 72, selection: { kind: "element", objectId: "effects-motion-card", ownerItemId: "effects-scene" }, panel: "inspector" },
    },
    {
      id: "editorial",
      phase: "Edit",
      title: "Trim media and move a layer",
      description: "Source time, composition placement and explicit visual lanes stay separate and inspectable.",
      try: "Front-trim Real media, move Editorial copy to another layer, then Undo both edits.",
      success: "The surviving first source frame stays fixed and each source-backed edit reverses cleanly.",
      target: { compositionKey: "editorial-lab", frame: 48, selection: { kind: "clip", objectId: "editorial-media" }, panel: "inspector" },
    },
    {
      id: "grade",
      phase: "Finish",
      title: "Grade and compare a LUT",
      description: "Browser-local grade and LUT processing is shared by preview, exact capture and export.",
      try: "Adjust the grade, hold B to compare bypass and capture the current frame.",
      success: "The exact snapshot contains the same look as the canvas preview.",
      target: { compositionKey: "grade-lab", frame: 48, selection: { kind: "clip", objectId: "teal-wash" }, panel: "inspector" },
    },
    {
      id: "nested-production",
      phase: "Edit",
      title: "Inspect the real nested hero edit",
      description: "The example production reel combines generated HTML, real media, a reusable alpha overlay and an end card.",
      try: "Open Main, inspect its child clips, then open LowerThird and return through the breadcrumb.",
      success: "Child timing remains relative to Main while source editing happens in the focused child.",
      target: { compositionKey: "main", frame: 220 },
    },
    {
      id: "cloth",
      phase: "Simulate",
      title: "Turn authored HTML into deterministic cloth",
      description: "A DOM poster becomes a canvas texture on a constrained mesh with wind, impulses, colliders and capture registration.",
      try: "Jump from frame 132 back to 24 and forward again; then capture frame 132.",
      success: "Checkpointed simulation returns to the same geometry and the cloth appears in the exact snapshot.",
      target: { compositionKey: "cloth-lab", frame: 132, selection: { kind: "clip", objectId: "cloth-scene" }, panel: "inspector" },
    },
    {
      id: "three",
      phase: "Simulate",
      title: "Switch native Three.js cameras",
      description: "A source-defined Three scene exposes both keyframed and procedural cameras as ordinary timeline clips.",
      try: "Inspect overview camera, then procedural orbit camera and scrub each non-linearly.",
      success: "Both cameras update from absolute time without accumulating transform drift.",
      target: { compositionKey: "world-lab", frame: 150, selection: { kind: "clip", objectId: "world-orbit" }, panel: "inspector" },
    },
    {
      id: "video-plane",
      phase: "Simulate",
      title: "Direct a video plane in 3D",
      description: "Cached video is placed on a source-backed plane with camera curves, look direction, lens, focus, depth of field and motion blur.",
      try: "Open 3D Rig Editor, switch camera pose and move LOOK AT with its gizmo, then Undo.",
      success: "The fitted preview updates without remounting and one gizmo gesture is one history entry.",
      target: { compositionKey: "HeroPlane3D.uizoom", frame: 30, selection: { kind: "clip", objectId: "plane-uizoom" }, panel: "inspector" },
    },
    {
      id: "generate",
      phase: "Generate",
      title: "Draft a take without spending",
      description: "Prompt, model, parameters and pinned take are source; generated outputs and provenance are immutable assets.",
      try: "Choose Add Take, edit the draft, switch away and return before explicitly choosing Generate.",
      success: "The same draft remains editable and no generation begins on navigation or parameter changes.",
      target: { compositionKey: "skyTimelapse", frame: 0 },
    },
    {
      id: "audio",
      phase: "Deliver",
      title: "Inspect frame-driven audio automation",
      description: "Audio compositions, media lanes and deterministic volume automation share the visual frame domain.",
      try: "Select the audio bed, scrub through its fade region and inspect its timeline lane.",
      success: "Volume follows the requested frame and the lane remains independently selectable.",
      target: { compositionKey: "audio-lab", frame: 190, selection: { kind: "clip", objectId: "audio-bed" }, panel: "inspector" },
    },
    {
      id: "source",
      phase: "Author",
      title: "Relate authored onFrame code to preview",
      description: "Typed controls and registered motion coexist with a first-class arbitrary onFrame escape hatch.",
      try: "Open Code for LowerThird and scrub its entrance and exit while reading the literal source.",
      success: "The source is understandable and random-access evaluation needs no playback history.",
      target: { compositionKey: "lower-third", frame: 12, selection: { kind: "element", objectId: "lower-third-copy", ownerItemId: "lower-third-content" }, panel: "code" },
    },
    {
      id: "cache",
      phase: "Deliver",
      title: "Inspect dependency fingerprints",
      description: "Content-addressed artifacts record declared source hashes and become stale only when an input changes.",
      try: "Open Cache, inspect a bake sidecar, make and undo a child edit, then check status again.",
      success: "Only dependent artifacts change status and Undo restores the original source fingerprint.",
      target: { compositionKey: "studio-playground", frame: 90, panel: "cache" },
    },
    {
      id: "agent",
      phase: "Deliver",
      title: "Check and capture through the Agent API",
      description: "Humans and coding agents use the same stable IDs, semantic commands, source revisions and exact browser-local capture path.",
      try: "Run Check, capture frame 90 twice and compare the returned PNG hashes.",
      success: "The project is ready, both hashes match and the captured composition ID is StudioPlayground.",
      target: { compositionKey: "studio-playground", frame: 90, panel: "agent" },
    },
  ],
};
