import type { StudioGuideDescriptor } from "framediff";

export const productionLabGuide: StudioGuideDescriptor = {
  id: "production-lab-tour-v1",
  title: "FrameDiff Production Lab",
  summary: "A source-backed walkthrough from direct manipulation to editorial, motion, finishing, generation, artifacts, exact frames and local delivery.",
  estimatedMinutes: 25,
  steps: [
    {
      id: "orientation",
      phase: "Start here",
      title: "See the whole production graph",
      description: "The overview is a real composition: nested chapters, generated media, an audio lane and an onFrame-driven chapter HUD all share one exact frame clock.",
      try: "Scrub across the full timeline and watch the chapter name and progress update without playing forward.",
      success: "Jumping to any frame immediately produces the right nested chapter and HUD state.",
      target: { compositionKey: "production-lab", frame: 90 },
    },
    {
      id: "canvas-move",
      phase: "Design",
      title: "Select, move and resize on canvas",
      description: "Stable IDs join canvas selection, Inspector state, source authority and Undo/Redo.",
      try: "Drag the MOVE card, resize it, use Shift for axis/aspect constraints and press Undo once.",
      success: "The gesture creates one readable data-fd source diff and one history entry.",
      target: { compositionKey: "direct-manipulation-lab", frame: 60, selection: { kind: "element", objectId: "move-card", ownerItemId: "lab-scene" }, panel: "inspector" },
    },
    {
      id: "materialize",
      phase: "Design",
      title: "Materialize computed geometry",
      description: "Computed CSS stays renderable and read-only until the user explicitly chooses first-party geometry authority.",
      try: "Select MATERIALIZE and choose Make movable, then drag it.",
      success: "Only that element gains explicit data-fd geometry; its existing CSS remains intact.",
      target: { compositionKey: "direct-manipulation-lab", frame: 60, selection: { kind: "element", objectId: "materialize-card", ownerItemId: "lab-scene" }, panel: "inspector" },
    },
    {
      id: "typography",
      phase: "Design",
      title: "Edit text and typography",
      description: "Direct text editing and typed Inspector controls compile to the same source-backed property ABI.",
      try: "Change the headline text, font size, weight, color and letter spacing; then refresh.",
      success: "The exact values survive HMR and appear as readable data-fd attributes.",
      target: { compositionKey: "rich-properties-lab", frame: 60, selection: { kind: "element", objectId: "rich-headline", ownerItemId: "rich-scene" }, panel: "inspector" },
    },
    {
      id: "fills-layout",
      phase: "Design",
      title: "Build fills and flex layout",
      description: "Gradients, image fills, flex, spacing, opacity and blend controls remain portable authored source.",
      try: "Change the gradient angle/stops, then select the image panel and choose a manifest asset from Media.",
      success: "The fill updates live and source stores asset:// identity instead of a machine-local cache URL.",
      target: { compositionKey: "rich-properties-lab", frame: 60, selection: { kind: "element", objectId: "gradient-panel", ownerItemId: "rich-scene" }, panel: "inspector" },
    },
    {
      id: "media",
      phase: "Assets",
      title: "Inspect portable media and proxies",
      description: "Media identity, original/proxy availability and content hashes stay connected from import through render.",
      try: "Open Media, inspect an asset, then hover its timeline badges: ● local, ⇣ remote, ! missing, proxy, t# pinned take, ✓/~ bake state, ↳ nested and fx effects.",
      success: "The UI labels local, remote or proxy state without exposing a persisted local URL.",
      target: { compositionKey: "editorial-lab", frame: 45, panel: "media" },
    },
    {
      id: "front-trim",
      phase: "Editorial",
      title: "Front-trim real media",
      description: "The left edge advances the source in-point in seconds using composition FPS and playback rate.",
      try: "Pull the left trim handle of Real media, then Undo and Redo.",
      success: "The surviving first source frame is unchanged and placement plus trimStart commit atomically.",
      target: { compositionKey: "editorial-lab", frame: 48, selection: { kind: "clip", objectId: "editorial-media" }, panel: "inspector" },
    },
    {
      id: "layers",
      phase: "Editorial",
      title: "Move persistent visual layers",
      description: "Vertical lanes reflect authored data-fd-layer authority rather than overlap-derived guesses.",
      try: "Drag Editorial copy vertically to a different visual lane, then reload the composition.",
      success: "Stacking changes without changing horizontal timing, and reload preserves the lane.",
      target: { compositionKey: "editorial-lab", frame: 72, selection: { kind: "clip", objectId: "editorial-copy" }, panel: "inspector" },
    },
    {
      id: "keys",
      phase: "Motion",
      title: "Edit a frame-authored GSAP tween",
      description: "Registered GSAP is a source adapter over FrameDiff's absolute random-access frame clock.",
      try: "Drag a title-enter key diamond, change its ease, then jump backward and forward across it.",
      success: "Preview and export seek the same authored frame; no wall-clock state leaks in.",
      target: { compositionKey: "gsap-motion-lab", frame: 20, selection: { kind: "animation", objectId: "title-enter" }, panel: "inspector" },
    },
    {
      id: "path",
      phase: "Motion",
      title: "Shape an arc or record a gesture",
      description: "Motion paths, handles and gesture samples are composition-coordinate, frame-bounded source data.",
      try: "Select product-flight, make an arc, drag a tangent, or record and preview a gesture before committing.",
      success: "The path survives HMR and the whole gesture is one grouped Undo entry.",
      target: { compositionKey: "gsap-motion-lab", frame: 100, selection: { kind: "animation", objectId: "product-flight" }, panel: "inspector" },
    },
    {
      id: "unroll",
      phase: "Motion",
      title: "Unroll a computed helper safely",
      description: "AST call-site isolation and the runtime trace bridge derived code into explicit editable tweens.",
      try: "Choose Unroll to edit for helper-dots, inspect the three operations, then Undo.",
      success: "The normalized trace stays identical and Undo restores the original helper call exactly.",
      target: { compositionKey: "gsap-motion-lab", frame: 72, selection: { kind: "animation", objectId: "helper-dots" }, panel: "inspector" },
    },
    {
      id: "grade",
      phase: "Finishing",
      title: "Grade and LUT locally",
      description: "WebGPU grade/LUT processing uses the same browser-local capture path as preview, exact snapshots and export.",
      try: "Adjust the grade layer, hold B to compare bypass, and scrub between graded shots.",
      success: "The look toggles instantly and the same grade appears in an exact captured frame.",
      target: { compositionKey: "grade-lab", frame: 48, selection: { kind: "clip", objectId: "teal-wash" }, panel: "inspector" },
    },
    {
      id: "camera",
      phase: "Finishing",
      title: "Direct the imported 3D camera shot",
      description: "The full-screen 3D Rig Editor puts the cached video frame on its authored plane and exposes source-backed A/B camera, look direction, focus, plane, lens and finishing controls.",
      try: "Open 3D Rig Editor, switch to B · END, move LOOK AT with its XYZ gizmo, inspect SHOT POV, then Undo.",
      success: "One gizmo gesture is one atomic source edit and Undo entry; the exact fitted preview, LUT and local render path update without a canvas reload.",
      target: { compositionKey: "HeroPlane3D.uizoom", frame: 30, selection: { kind: "clip", objectId: "plane-uizoom" }, panel: "inspector" },
    },
    {
      id: "generative",
      phase: "Generate",
      title: "Review a pinned generative take",
      description: "Prompt, model, parameters and take pin are source; immutable output and provenance live in the asset manifest.",
      try: "Inspect the existing take, change a draft parameter, and confirm generation never starts until you explicitly press Generate.",
      success: "The draft becomes stale without spending money or changing the pinned output.",
      target: { compositionKey: "skyTimelapse", frame: 0 },
    },
    {
      id: "source",
      phase: "Source",
      title: "Follow an authored onFrame composition",
      description: "Arbitrary onFrame code remains a first-class escape hatch beside typed controls and registered motion.",
      try: "Open Code for LowerThird, scrub its entrance/exit and relate the literal source to the preview.",
      success: "Random-access scrubbing evaluates the correct state without converting the composition to GSAP.",
      target: { compositionKey: "lower-third", frame: 12, selection: { kind: "element", objectId: "lower-third-copy", ownerItemId: "lower-third-content" }, panel: "code" },
    },
    {
      id: "artifacts",
      phase: "Deliver",
      title: "Inspect bakes and fingerprints",
      description: "Content-addressed artifacts record every declared source hash and become stale only when an input changes.",
      try: "Open Cache, inspect a bake sidecar, then make and undo a child edit.",
      success: "Only dependent artifacts change status; undo returns the original source fingerprint.",
      target: { compositionKey: "production-lab", frame: 1260, panel: "cache" },
    },
    {
      id: "agent-render",
      phase: "Deliver",
      title: "Check, snapshot and render",
      description: "Humans and agents use the same IDs, source revisions, semantic commands, exact capture and local render pipeline.",
      try: "Run Agent API check, capture the same frame twice, then use Render MP4 when you are ready.",
      success: "The project is READY, repeated PNG hashes match, and export remains browser-local.",
      target: { compositionKey: "production-lab", frame: 90, panel: "agent" },
    },
  ],
};
