import type { StudioGuideDescriptor } from "framediff";

export const productionLabGuide: StudioGuideDescriptor = {
  id: "production-lab-tour-v1",
  title: "FrameDiff Production Lab",
  summary: "A source-backed walkthrough from direct manipulation to editorial, motion, finishing, generation, artifacts, exact frames and local delivery.",
  estimatedMinutes: 25,
  steps: [
    {
      id: "orientation",
      phase: "Start here",
      title: "See the whole production graph",
      description: "The overview is a real composition: nested chapters, generated media, an audio lane and an onFrame-driven chapter HUD all share one exact frame clock.",
      try: "Scrub across the full timeline and watch the chapter name and progress update without playing forward.",
      success: "Jumping to any frame immediately produces the right nested chapter and HUD state.",
      target: { compositionKey: "production-lab", frame: 90 },
    },
    {
      id: "canvas-move",
      phase: "Design",
      title: "Select, move and resize on canvas",
      description: "Stable IDs join canvas selection, composition JSON, Inspector state and Undo/Redo.",
      try: "Drag the MOVE card, resize it, use Shift for axis/aspect constraints and press Undo once.",
      success: "The gesture creates one readable JSON diff and one history entry without rebuilding the project.",
      target: { compositionKey: "direct-manipulation-lab", frame: 60, selection: { kind: "element", objectId: "move-card" }, panel: "inspector" },
    },
    {
      id: "direct-settings",
      phase: "Design",
      title: "Edit document-backed settings directly",
      description: "Position, size, rotation and copy are already authoritative composition JSON; no activation mode is required.",
      try: "Select SETTINGS and drag it immediately, then change one of its properties in the Inspector.",
      success: "Both edits update the same JSON object and the preview patches in place.",
      target: { compositionKey: "direct-manipulation-lab", frame: 60, selection: { kind: "element", objectId: "settings-card" }, panel: "inspector" },
    },
    {
      id: "typography",
      phase: "Design",
      title: "Edit text and typography",
      description: "Direct text editing and typed Inspector controls update the same JSON-backed property ABI.",
      try: "Change the headline text, font size, weight, color and letter spacing; then refresh.",
      success: "The exact values survive HMR as readable JSON and drive preview and exact render alike.",
      target: { compositionKey: "rich-properties-lab", frame: 60, selection: { kind: "element", objectId: "rich-headline" }, panel: "inspector" },
    },
    {
      id: "fills-layout",
      phase: "Design",
      title: "Build fills and flex layout",
      description: "Gradients, image fills, flex, spacing, opacity and blend controls remain portable composition JSON.",
      try: "Change the gradient angle/stops, then select the image panel and choose a manifest asset from Media.",
      success: "The fill updates live and source stores asset:// identity instead of a machine-local cache URL.",
      target: { compositionKey: "rich-properties-lab", frame: 60, selection: { kind: "element", objectId: "gradient-panel" }, panel: "inspector" },
    },
    {
      id: "media",
      phase: "Assets",
      title: "Inspect portable media and proxies",
      description: "Media identity, original/proxy availability and content hashes stay connected from import through render.",
      try: "Open Media, inspect an asset, then hover its timeline badges: ● local, ⇣ remote, ! missing, proxy, t# pinned take, ✓/~ bake state, ↳ nested and fx effects.",
      success: "The UI labels local, remote or proxy state without exposing a persisted local URL.",
      target: { compositionKey: "editorial-lab", frame: 45, panel: "media" },
    },
    {
      id: "front-trim",
      phase: "Editorial",
      title: "Front-trim real media",
      description: "The left edge advances the source in-point in seconds using composition FPS and playback rate.",
      try: "Pull the left trim handle of Real media, then Undo and Redo.",
      success: "The surviving first source frame is unchanged and placement plus trimStart commit atomically.",
      target: { compositionKey: "editorial-lab", frame: 48, selection: { kind: "clip", objectId: "editorial-media" }, panel: "inspector" },
    },
    {
      id: "layers",
      phase: "Editorial",
      title: "Move persistent visual layers",
      description: "Vertical lanes reflect authored data-fd-layer authority rather than overlap-derived guesses.",
      try: "Drag Editorial copy vertically to a different visual lane, then reload the composition.",
      success: "Stacking changes without changing horizontal timing, and reload preserves the lane.",
      target: { compositionKey: "editorial-lab", frame: 72, selection: { kind: "clip", objectId: "editorial-copy" }, panel: "inspector" },
    },
    {
      id: "keys",
      phase: "Motion",
      title: "Inspect frame-authored GSAP motion",
      description: "Project-owned GSAP remains a paused runtime over FrameDiff's absolute random-access frame clock.",
      try: "Edit the JSON-backed title copy, then jump backward and forward across its entrance.",
      success: "The copy persists and the same authored frame resolves without wall-clock state.",
      target: { compositionKey: "gsap-motion-lab", frame: 20, selection: { kind: "element", objectId: "motion-title-lead" }, panel: "inspector" },
    },
    {
      id: "path",
      phase: "Motion",
      title: "Inspect an authored motion path",
      description: "The project-owned path is composition-coordinate and frame-bounded while its label remains JSON data.",
      try: "Edit the product label, scrub across its flight, then Undo the text edit.",
      success: "The label reverses cleanly and non-linear scrubbing returns the product to the same point.",
      target: { compositionKey: "gsap-motion-lab", frame: 100, selection: { kind: "element", objectId: "path-product" }, panel: "inspector" },
    },
    {
      id: "unroll",
      phase: "Motion",
      title: "Verify computed helper motion",
      description: "A project helper expands deterministic source behavior without exposing a generic source rewrite path.",
      try: "Scrub around frame 72, select the first trace dot, then return to the same frame.",
      success: "The expanded helper motion resolves identically after the non-linear seek.",
      target: { compositionKey: "gsap-motion-lab", frame: 72, selection: { kind: "element", objectId: "trace-a" }, panel: "inspector" },
    },
    {
      id: "grade",
      phase: "Finishing",
      title: "Grade and LUT locally",
      description: "WebGPU grade/LUT processing uses the same browser-local capture path as preview, exact snapshots and export.",
      try: "Adjust the grade layer, hold B to compare bypass, and scrub between graded shots.",
      success: "The look toggles instantly and the same grade appears in an exact captured frame.",
      target: { compositionKey: "grade-lab", frame: 48, selection: { kind: "clip", objectId: "teal-wash" }, panel: "inspector" },
    },
    {
      id: "camera",
      phase: "Finishing",
      title: "Direct the imported 3D camera shot",
      description: "The full-screen 3D Rig Editor puts the cached video frame on its authored plane and exposes source-backed A/B camera, look direction, focus, plane, lens and finishing controls.",
      try: "Open 3D Rig Editor, switch to B · END, move LOOK AT with its XYZ gizmo, inspect SHOT POV, then Undo.",
      success: "One gizmo gesture is one atomic source edit and Undo entry; the exact fitted preview, LUT and local render path update without a canvas reload.",
      target: { compositionKey: "HeroPlane3D.uizoom", frame: 30, selection: { kind: "clip", objectId: "plane-uizoom" }, panel: "inspector" },
    },
    {
      id: "generative",
      phase: "Generate",
      title: "Review a pinned generative take",
      description: "Prompt, model, parameters and take pin are source; immutable output and provenance live in the asset manifest.",
      try: "Inspect the existing take, change a draft parameter, and confirm generation never starts until you explicitly press Generate.",
      success: "The draft becomes stale without spending money or changing the pinned output.",
      target: { compositionKey: "skyTimelapse", frame: 0 },
    },
    {
      id: "source",
      phase: "Source",
      title: "Inspect an authored onFrame composition",
      description: "Arbitrary onFrame code remains a first-class escape hatch beside typed controls and registered motion.",
      try: "Inspect the LowerThird copy and scrub its entrance and exit in the preview.",
      success: "Random-access scrubbing evaluates the correct state without converting the composition to GSAP.",
      target: { compositionKey: "lower-third", frame: 12, selection: { kind: "element", objectId: "lower-third-copy" }, panel: "inspector" },
    },
    {
      id: "artifacts",
      phase: "Deliver",
      title: "Inspect bakes and fingerprints",
      description: "Content-addressed artifacts record every declared source hash and become stale only when an input changes.",
      try: "Open Cache, inspect a bake sidecar, then make and undo a child edit.",
      success: "Only dependent artifacts change status; undo returns the original source fingerprint.",
      target: { compositionKey: "production-lab", frame: 1260, panel: "cache" },
    },
    {
      id: "agent-render",
      phase: "Deliver",
      title: "Check, snapshot and render",
      description: "Humans and agents use the same IDs, source revisions, semantic commands, exact capture and local render pipeline.",
      try: "Run Agent API check, capture the same frame twice, then use Render MP4 when you are ready.",
      success: "The project is READY, repeated PNG hashes match, and export remains browser-local.",
      target: { compositionKey: "production-lab", frame: 90, panel: "agent" },
    },
  ],
};
