import type { CompRegistry } from "framediff";
import { blazerRelight } from "./gen/blazerRelight.gen";
import { skyTimelapse } from "./gen/skyTimelapse.gen";
import { baseRegistry, composition } from "./compositions";
import { testGenerateComp } from "./TestGenerate";
import { asdfComp } from "./Asdf";
import { sdasdfComp } from "./Sdasdf";
import { testComp } from "./Test.gen";
import { blahComp } from "./Blah.gen";
export { composition };
export const COMPOSITIONS: CompRegistry = { ...baseRegistry, skyTimelapse, blazerRelight, "test-generate": testGenerateComp, "asdf": asdfComp, "sdasdf": sdasdfComp, "test": testComp, "blah": blahComp, };
