import type { CompRegistry } from "framediff";
import { heroRawComp } from "./HeroRaw";
import { heroPlaneShotComps } from "./HeroPlane3D";
import {
  composition,
  directManipulationLabComp,
  editorialLabComp,
  endCardComp,
  gradeLabComp,
  gsapMotionLabComp,
  heroExcerptComp,
  heroFootageComp,
  heroRebuiltComp,
  heroScriptComp,
  lowerThirdComp,
  productionLabComp,
  richPropertiesLabComp,
} from "./StaticCompositions";
import {
  audioLabComp,
  authoringChapterComp,
  clothLabComp,
  coverageMapComp,
  editorialChapterComp,
  effectsChapterComp,
  packageEffectsLabComp,
  pipelineChapterComp,
  studioPlaygroundComp,
  worldLabComp,
} from "./playground/StudioPlayground";
import { planLabComp } from "./playground/PlanLab";
import { boardLabComp } from "./playground/BoardLab";

export {
  composition,
  directManipulationLabComp,
  editorialLabComp,
  endCardComp,
  gradeLabComp,
  gsapMotionLabComp,
  heroExcerptComp,
  heroFootageComp,
  heroPlaneShotComps,
  heroRawComp,
  heroRebuiltComp,
  heroScriptComp,
  lowerThirdComp,
  productionLabComp,
  richPropertiesLabComp,
  studioPlaygroundComp,
  coverageMapComp,
  authoringChapterComp,
  editorialChapterComp,
  effectsChapterComp,
  pipelineChapterComp,
  packageEffectsLabComp,
  clothLabComp,
  worldLabComp,
  audioLabComp,
  planLabComp,
  boardLabComp,
};

export const baseRegistry: CompRegistry = {
  "studio-playground": studioPlaygroundComp,
  "coverage-map": coverageMapComp,
  "authoring-chapter": authoringChapterComp,
  "editorial-chapter": editorialChapterComp,
  "effects-chapter": effectsChapterComp,
  "pipeline-chapter": pipelineChapterComp,
  "package-effects-lab": packageEffectsLabComp,
  "cloth-lab": clothLabComp,
  "world-lab": worldLabComp,
  "audio-lab": audioLabComp,
  "plan-lab": planLabComp,
  "board-lab": boardLabComp,
  "production-lab": productionLabComp,
  main: composition,
  "hero-script": heroScriptComp,
  hero: heroRawComp,
  "hero-raw": heroRawComp,
  "hero-footage-reference": heroFootageComp,
  "hero-rebuilt": heroRebuiltComp,
  "lower-third": lowerThirdComp,
  "end-card": endCardComp,
  excerpt: heroExcerptComp,
  "grade-lab": gradeLabComp,
  "direct-manipulation-lab": directManipulationLabComp,
  "rich-properties-lab": richPropertiesLabComp,
  "editorial-lab": editorialLabComp,
  "gsap-motion-lab": gsapMotionLabComp,
  ...heroPlaneShotComps,
};
